// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWc6i9mYSql-e5-NNJZntoKXDBnH20eXE',
    appId: '1:19121857095:web:a9daff5bca0fb3e60e0762',
    messagingSenderId: '19121857095',
    projectId: 'edme-2f1c2',
    authDomain: 'edme-2f1c2.firebaseapp.com',
    storageBucket: 'edme-2f1c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmqsZZhjQg6roynqtkfuzGlWQLF27PiRU',
    appId: '1:19121857095:android:597b4bb62ec458580e0762',
    messagingSenderId: '19121857095',
    projectId: 'edme-2f1c2',
    storageBucket: 'edme-2f1c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAibX_DwJGcScur8LV-SQsfuXWY-liC8sM',
    appId: '1:19121857095:ios:0e93a1361d8ca9520e0762',
    messagingSenderId: '19121857095',
    projectId: 'edme-2f1c2',
    storageBucket: 'edme-2f1c2.appspot.com',
    iosBundleId: 'com.example.edme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAibX_DwJGcScur8LV-SQsfuXWY-liC8sM',
    appId: '1:19121857095:ios:5bc61885b41f5e250e0762',
    messagingSenderId: '19121857095',
    projectId: 'edme-2f1c2',
    storageBucket: 'edme-2f1c2.appspot.com',
    iosBundleId: 'com.example.edme.RunnerTests',
  );
}
